<?php
return [
    'genders' => ['male', 'female', 'others'],
    'media_types' => ['image', 'audio', 'video', 'document'],
    'address_types' => ['current', 'previous'],
    'contact_types' => ['primary', 'secondary', 'emergency'],
    'gift_plans_statuses' => ['planed' => 'primary', 'accepted' => 'success', 'sent' => 'secondary'],
    'currencies' => ['GBP', 'USD', 'BDT'],
    'occasions' => [
        "Birthday",
        "Wedding Anniversary",
        "Engagement",
        "Wedding Day",
        "Birth of New Baby",
        "Promotion",
        "Job Anniversary",
        "New Job",
        "New Employee/Welcome",
        "Good Bye/Moving",
        "New Year's Day",
        "Valentine's Day",
        "Mothers' Day",
        "Fathers' Day",
        "Easter",
        "Christmas festival",
        "Graduation",
        "Thank You/Appreciation",
        "other"
    ],
    'relations' => [
        'father',
        'mother',
        'son',
        'daughter',
        'husband',
        'wife',
        'brother',
        'sister',
        'grandfather',
        'grandmother',
        'grandson',
        'granddaughter',
        'uncle',
        'aunt',
        'nephew',
        'niece',
        'cousin',
        'other'
    ]
];